default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: angular_app_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: angular_app_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: angular_app_production
  pool: 5
  username: 
  password:
